'use strict';

const SCHOLARSHIP_SOURCE_REGISTRY = [
  {
    id: 'daad',
    label: 'DAAD Germany scholarship database',
    url: 'https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/',
    domains: ['daad.de'],
    tier: 'official',
    fit: ['Germany', 'graduate', 'research', 'fully funded'],
  },
  {
    id: 'fulbright',
    label: 'Fulbright foreign student program',
    url: 'https://foreign.fulbrightonline.org/',
    domains: ['fulbrightonline.org', 'fulbright.hu'],
    tier: 'official',
    fit: ['United States', 'graduate', 'research'],
  },
  {
    id: 'fulbright_hungary',
    label: 'Fulbright Hungary',
    url: 'https://fulbright.hu/',
    domains: ['fulbright.hu'],
    tier: 'official',
    fit: ['Hungary', 'United States', 'graduate', 'research'],
  },
  {
    id: 'erasmus_mundus',
    label: 'Erasmus Mundus catalogue',
    url: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    domains: ['eacea.ec.europa.eu', 'europa.eu'],
    tier: 'official',
    fit: ['Europe', 'masters', 'fully funded'],
  },
  {
    id: 'maeci',
    label: 'Italy MAECI grants',
    url: 'https://studyinitaly.esteri.it/ListaBandi',
    domains: ['studyinitaly.esteri.it', 'esteri.it'],
    tier: 'official',
    fit: ['Italy', 'graduate', 'research'],
  },
  {
    id: 'campus_france',
    label: 'Campus France scholarship catalogue',
    url: 'https://www.campusfrance.org/en/bursaries-foreign-students',
    domains: ['campusfrance.org'],
    tier: 'official',
    fit: ['France', 'masters', 'research'],
  },
  {
    id: 'chevening',
    label: 'Chevening scholarships',
    url: 'https://www.chevening.org/scholarships/',
    domains: ['chevening.org'],
    tier: 'official',
    fit: ['United Kingdom', 'masters', 'fully funded'],
  },
  {
    id: 'commonwealth',
    label: 'Commonwealth scholarships',
    url: 'https://cscuk.fcdo.gov.uk/scholarships/',
    domains: ['cscuk.fcdo.gov.uk'],
    tier: 'official',
    fit: ['United Kingdom', 'masters', 'phd', 'fully funded'],
  },
  {
    id: 'gates_cambridge',
    label: 'Gates Cambridge',
    url: 'https://www.gatescambridge.org/',
    domains: ['gatescambridge.org'],
    tier: 'official',
    fit: ['United Kingdom', 'graduate', 'fully funded'],
  },
  {
    id: 'study_in_sweden',
    label: 'Study in Sweden scholarships',
    url: 'https://studyinsweden.se/scholarships/',
    domains: ['studyinsweden.se'],
    tier: 'official',
    fit: ['Sweden', 'masters'],
  },
  {
    id: 'study_in_nl',
    label: 'Study in NL scholarships',
    url: 'https://www.studyinnl.org/finances',
    domains: ['studyinnl.org'],
    tier: 'official',
    fit: ['Netherlands', 'masters'],
  },
  {
    id: 'pannonia',
    label: 'Pannonia scholarship programme',
    url: 'https://pannoniaosztondij.hu/about-the-pannonia-scholarship-programme',
    domains: ['pannoniaosztondij.hu'],
    tier: 'official',
    fit: ['Hungary', 'student mobility', 'Europe', 'international'],
  },
  {
    id: 'erasmus_plus',
    label: 'Erasmus+ student mobility',
    url: 'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/studying-abroad',
    domains: ['erasmus-plus.ec.europa.eu'],
    tier: 'official',
    fit: ['Hungary', 'student mobility', 'Europe'],
  },
  {
    id: 'ceepus',
    label: 'CEEPUS student mobility',
    url: 'https://en.tka.hu/central_european_exchange_programme_for_university_studies',
    domains: ['tka.hu'],
    tier: 'official',
    fit: ['Hungary', 'student mobility', 'Central Europe'],
  },
  {
    id: 'tka_bilateral',
    label: 'TKA bilateral state scholarships',
    url: 'https://tka.hu/international-programmes/4127/bilateral-state-scholarships',
    domains: ['tka.hu'],
    tier: 'official',
    fit: ['Hungary', 'student mobility', 'international'],
  },
  {
    id: 'stipendium_hungaricum',
    label: 'Stipendium Hungaricum',
    url: 'https://stipendiumhungaricum.hu/apply/',
    domains: ['stipendiumhungaricum.hu'],
    tier: 'official',
    fit: ['Hungary', 'international', 'fully funded'],
  },
  {
    id: 'scholars4dev',
    label: 'Scholars4Dev',
    url: 'https://www.scholars4dev.com/',
    domains: ['scholars4dev.com'],
    tier: 'aggregator',
    fit: ['global', 'fully funded'],
  },
  {
    id: 'international_scholarships',
    label: 'International Scholarships',
    url: 'https://www.internationalscholarships.com/',
    domains: ['internationalscholarships.com'],
    tier: 'aggregator',
    fit: ['global'],
  },
];

const JOB_SOURCE_REGISTRY = [
  {
    id: 'profession',
    label: 'Profession.hu',
    url: 'https://www.profession.hu/',
    domains: ['profession.hu'],
    tier: 'local_primary',
    fit: ['Budapest', 'Hungary', 'full-time', 'student'],
  },
  {
    id: 'minddiak',
    label: 'Mind-Diak student jobs',
    url: 'https://www.minddiak.hu/',
    domains: ['minddiak.hu'],
    tier: 'student_primary',
    fit: ['student', 'Budapest', 'part-time'],
  },
  {
    id: 'melodiak',
    label: 'Melo-Diak student jobs',
    url: 'https://melo-diak.hu/',
    domains: ['melo-diak.hu', 'melodiak.hu'],
    tier: 'student_primary',
    fit: ['student', 'part-time'],
  },
  {
    id: 'multijob',
    label: 'MultiJob student jobs',
    url: 'https://www.multijob.hu/',
    domains: ['multijob.hu'],
    tier: 'student_primary',
    fit: ['student', 'part-time'],
  },
  {
    id: 'humancentrum',
    label: 'Human Centrum jobs',
    url: 'https://humancentrum.hu/',
    domains: ['humancentrum.hu'],
    tier: 'local_primary',
    fit: ['Hungary', 'student', 'part-time'],
  },
  {
    id: 'randstad',
    label: 'Randstad Hungary',
    url: 'https://www.randstad.hu/allasok/',
    domains: ['randstad.hu'],
    tier: 'local_primary',
    fit: ['Hungary', 'Budapest', 'full-time'],
  },
  {
    id: 'cvonline',
    label: 'CVonline Hungary',
    url: 'https://www.cvonline.hu/',
    domains: ['cvonline.hu'],
    tier: 'local_primary',
    fit: ['Hungary', 'Budapest', 'full-time'],
  },
  {
    id: 'jobs_hu',
    label: 'Jobs.hu',
    url: 'https://www.jobs.hu/',
    domains: ['jobs.hu'],
    tier: 'local_primary',
    fit: ['Hungary', 'Budapest', 'full-time'],
  },
  {
    id: 'hays',
    label: 'Hays Hungary',
    url: 'https://www.hays.hu/en/job-search',
    domains: ['hays.hu'],
    tier: 'local_primary',
    fit: ['Hungary', 'Budapest', 'professional'],
  },
  {
    id: 'jooble',
    label: 'Jooble Hungary',
    url: 'https://hu.jooble.org/',
    domains: ['jooble.org'],
    tier: 'aggregator',
    fit: ['Hungary', 'Budapest', 'part-time', 'remote'],
  },
  {
    id: 'nofluffjobs',
    label: 'No Fluff Jobs',
    url: 'https://nofluffjobs.com/',
    domains: ['nofluffjobs.com'],
    tier: 'tech_primary',
    fit: ['AI', 'developer', 'remote', 'hybrid'],
  },
  {
    id: 'remoteok',
    label: 'Remote OK',
    url: 'https://remoteok.com/',
    domains: ['remoteok.com'],
    tier: 'remote_primary',
    fit: ['remote', 'AI', 'writing', 'creative', 'developer'],
  },
  {
    id: 'remotive',
    label: 'Remotive remote jobs',
    url: 'https://remotive.com/remote-jobs',
    domains: ['remotive.com'],
    tier: 'remote_primary',
    fit: ['remote', 'AI', 'writing', 'creative', 'developer'],
  },
  {
    id: 'arbeitnow',
    label: 'Arbeitnow EU jobs',
    url: 'https://www.arbeitnow.com/',
    domains: ['arbeitnow.com'],
    tier: 'eu_primary',
    fit: ['Europe', 'remote', 'AI', 'creative', 'developer'],
  },
  {
    id: 'linkedin',
    label: 'LinkedIn Jobs',
    url: 'https://www.linkedin.com/jobs/',
    domains: ['linkedin.com'],
    tier: 'missing_high_value',
    fit: ['research labs', 'assistant', 'AI', 'international'],
  },
  {
    id: 'euraxess',
    label: 'EURAXESS research jobs',
    url: 'https://euraxess.ec.europa.eu/jobs',
    domains: ['euraxess.ec.europa.eu'],
    tier: 'missing_high_value',
    fit: ['research', 'Europe', 'university labs'],
  },
  {
    id: 'wellfound',
    label: 'Wellfound startups',
    url: 'https://wellfound.com/jobs',
    domains: ['wellfound.com'],
    tier: 'missing_high_value',
    fit: ['AI startups', 'remote', 'creative tech'],
  },
  {
    id: 'huggingface_workable',
    label: 'Hugging Face jobs',
    url: 'https://apply.workable.com/huggingface/',
    domains: ['apply.workable.com', 'huggingface.co'],
    tier: 'missing_high_value',
    fit: ['AI', 'remote', 'open source'],
  },
];

function getScholarshipSourceRegistry() {
  return SCHOLARSHIP_SOURCE_REGISTRY.map((source) => ({ ...source }));
}

function getJobSourceRegistry() {
  return JOB_SOURCE_REGISTRY.map((source) => ({ ...source }));
}

module.exports = {
  getScholarshipSourceRegistry,
  getJobSourceRegistry,
};
